import {Colors, Fuentes} from '../../Themes';
export default styles = {
    imageBg: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    viewLogin: {
        width: '80%',
        height: '80%',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: Colors.opacolight,
        borderRadius: 10,
        padding: 10,
    },
    title: {
        color: Colors.third,
        fontSize: 25,
        fontWeight: 'bold',
        marginBottom: 10,
        fontFamily: Fuentes.fuente,
    },
    texto: {
        color: Colors.third,
        fontSize: 18,
        textAlign: 'center',
        fontFamily: Fuentes.fuente,
    },
    textInput: {
        marginTop: 20,
        paddingHorizontal: 10,
        width: '70%',
        height: Platform.OS === 'ios' ? 30: 40,
        borderRadius: 5,
        backgroundColor: Colors.third,
        //fontFamily: Fuentes.fuente,
        //fontSize: 20,
        //paddingTop: 4,
    },
    picker: {
        height: 50,
        width: '70%',
        color: Colors.third,
        //marginTop: Platform.OS === 'ios' ? 0: 10,
    },
    imageBtn: {
        width: '100%',
        height: 40,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    btn: {
        marginTop: 20,
        width: '60%',
        height: 40,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: Colors.accentColor,
        shadowColor: Colors.gray,
        shadowColor: Colors.secondary,
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
        borderWidth: 1,
        borderColor: Colors.prymary,
    },
    textBtn: {
        color: Colors.third,
        fontSize: 20,
        fontWeight: 'bold',
        fontFamily: Fuentes.fuente,
        marginTop: Platform.OS === 'ios' ? 10: 0,
    },
    viewPicker: {
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
        position: 'relative',
        //paddingBottom: 100,
        marginBottom: Platform.OS === 'ios' ? 150 : 10,
        marginTop: Platform.OS === 'ios' ? -20: 0,
    },
    aceptaTerminos: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    checkBox: {
       height: 20, 
    },
    btnDisable: {
        position: 'absolute',
        top: -1,
        left: -1,
        bottom: -1,
        right: -1,
        backgroundColor: Colors.opacolight,
        borderRadius: 10,
    }
}